version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      net-pihole:
        ipv4_address: 172.24.0.2
    environment:
      TZ: 'America/New_York'
      DNS1: 172.24.0.3#5053
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 7000:80/tcp
    volumes:
      - ./pihole/etc/pihole/:/etc/pihole/
      - ./pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: klutchell/unbound
    networks:
      net-pihole:
        ipv4_address: 172.24.0.3
    volumes:
      - ./unbound:/opt/unbound/etc/unbound
    ports:
      - 5053:5053/udp
    restart: unless-stopped

networks:
  net-pihole:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/29
