version: "2.1"
services:
  beets:
    image: ghcr.io/linuxserver/beets:nightly
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /mnt/home/dylan/Music:/music
      - /mnt/files/downloads/music:/downloads
    restart: unless-stopped
